"""empty message

Revision ID: 0c2975a21583
Revises: 0e9ca37a9e0d
Create Date: 2025-09-26 11:57:18.297182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2975a21583'
down_revision: Union[str, Sequence[str], None] = '0e9ca37a9e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_criteria', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_criteria', 'title')
    # ### end Alembic commands ###
