"""empty message

Revision ID: 0e9ca37a9e0d
Revises: 3bd4655b75bb
Create Date: 2025-09-26 11:53:41.176801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9ca37a9e0d'
down_revision: Union[str, Sequence[str], None] = '3bd4655b75bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_subjects_education_code_fkey'), 'student_subjects', type_='foreignkey')
    op.drop_column('student_subjects', 'education_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('education_code', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('student_subjects_education_code_fkey'), 'student_subjects', 'education_years', ['education_code'], ['code'])
    # ### end Alembic commands ###
