"""empty message

Revision ID: 103f3387e6ab
Revises: 879d4cf75619
Create Date: 2025-09-25 01:48:31.026364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103f3387e6ab'
down_revision: Union[str, Sequence[str], None] = '879d4cf75619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
