"""empty message

Revision ID: 150f53de1438
Revises: b1c25d4704ee
Create Date: 2025-09-26 11:44:41.390266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150f53de1438'
down_revision: Union[str, Sequence[str], None] = 'b1c25d4704ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_subjects',
    sa.Column('student_id', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_type_code', sa.String(), nullable=False),
    sa.Column('subject_type_name', sa.String(), nullable=False),
    sa.Column('exam_finish_code', sa.String(), nullable=False),
    sa.Column('exam_finish_name', sa.String(), nullable=False),
    sa.Column('semester_code', sa.String(), nullable=False),
    sa.Column('semester_name', sa.String(), nullable=False),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('total_acload', sa.Integer(), nullable=True),
    sa.Column('total_point', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('finish_credit_status', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subjects')
    # ### end Alembic commands ###
