"""empty message

Revision ID: 256eb521675f
Revises: 4d2da426a77e
Create Date: 2025-09-28 15:49:41.156337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256eb521675f'
down_revision: Union[str, Sequence[str], None] = '4d2da426a77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_types', sa.Column('can_upload', sa.Boolean(), nullable=False))
    op.add_column('achievement_types', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_types', 'description')
    op.drop_column('achievement_types', 'can_upload')
    # ### end Alembic commands ###
