"""empty message

Revision ID: 2974fec0732b
Revises: c366a30fc181
Create Date: 2025-09-26 11:35:27.845871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2974fec0732b'
down_revision: Union[str, Sequence[str], None] = 'c366a30fc181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_achievements', 'semester_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_achievements', 'semester_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
