"""empty message

Revision ID: 2c1309ef88ac
Revises: fb47e6a773ec
Create Date: 2025-09-26 09:12:34.993169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1309ef88ac'
down_revision: Union[str, Sequence[str], None] = 'fb47e6a773ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('student_id_number', sa.String(length=512), nullable=False))
    op.drop_constraint(op.f('student_achievements_student_id_fkey'), 'student_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'student_achievements', 'students', ['student_id_number'], ['student_id_number'])
    op.drop_column('student_achievements', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('student_achievements_student_id_fkey'), 'student_achievements', 'students', ['student_id'], ['id'])
    op.drop_column('student_achievements', 'student_id_number')
    # ### end Alembic commands ###
