"""empty message

Revision ID: 2d5bb27193ce
Revises: fe1c0a346fe9
Create Date: 2025-09-28 03:19:33.943918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5bb27193ce'
down_revision: Union[str, Sequence[str], None] = 'fe1c0a346fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('education_year', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semesters', 'education_year')
    # ### end Alembic commands ###
