"""empty message

Revision ID: 31a96964a8d3
Revises: 6d0bf1f82922
Create Date: 2025-09-25 01:44:33.750666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a96964a8d3'
down_revision: Union[str, Sequence[str], None] = '6d0bf1f82922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_code',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'year_of_enter',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'year_of_enter',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'department_code',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
