"""empty message

Revision ID: 32d26c2de502
Revises: 0c2975a21583
Create Date: 2025-09-26 12:02:49.457281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d26c2de502'
down_revision: Union[str, Sequence[str], None] = '0c2975a21583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('exam_finish_name', sa.String(), nullable=False))
    op.drop_column('student_subjects', 'exam_finish_namse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('exam_finish_namse', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('student_subjects', 'exam_finish_name')
    # ### end Alembic commands ###
