"""empty message

Revision ID: 3bd4655b75bb
Revises: 150f53de1438
Create Date: 2025-09-26 11:53:15.111450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd4655b75bb'
down_revision: Union[str, Sequence[str], None] = '150f53de1438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('exam_finish_namse', sa.String(), nullable=False))
    op.add_column('student_subjects', sa.Column('education_code', sa.String(length=512), nullable=False))
    op.create_foreign_key(None, 'student_subjects', 'education_years', ['education_code'], ['code'])
    op.create_foreign_key(None, 'student_subjects', 'semesters', ['semester_code'], ['code'])
    op.drop_column('student_subjects', 'semester_name')
    op.drop_column('student_subjects', 'exam_finish_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('exam_finish_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('student_subjects', sa.Column('semester_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_subjects', type_='foreignkey')
    op.drop_constraint(None, 'student_subjects', type_='foreignkey')
    op.drop_column('student_subjects', 'education_code')
    op.drop_column('student_subjects', 'exam_finish_namse')
    # ### end Alembic commands ###
