"""empty message

Revision ID: 4d2da426a77e
Revises: c8a3d237b821
Create Date: 2025-09-28 15:41:42.793386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2da426a77e'
down_revision: Union[str, Sequence[str], None] = 'c8a3d237b821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_types', sa.Column('type', sa.String(length=20), nullable=False))
    op.drop_column('achievement_types', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_types', sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('achievement_types', 'type')
    # ### end Alembic commands ###
