"""empty message

Revision ID: 560b22cf9a03
Revises: 6fa13f390c82
Create Date: 2025-09-27 16:06:13.421008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560b22cf9a03'
down_revision: Union[str, Sequence[str], None] = '6fa13f390c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('level_code', sa.String(length=512), nullable=False))
    op.drop_constraint(op.f('student_achievements_semester_code_fkey'), 'student_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'student_achievements', 'levels', ['level_code'], ['code'])
    op.drop_column('student_achievements', 'semester_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('semester_code', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('student_achievements_semester_code_fkey'), 'student_achievements', 'semesters', ['semester_code'], ['code'])
    op.drop_column('student_achievements', 'level_code')
    # ### end Alembic commands ###
