"""empty message

Revision ID: 612ca6c55dfa
Revises: d6e426a773d4
Create Date: 2025-09-26 02:06:36.404372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612ca6c55dfa'
down_revision: Union[str, Sequence[str], None] = 'd6e426a773d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student_achievements', 'education_years', ['year_code'], ['code'])
    op.create_foreign_key(None, 'student_achievements', 'semesters', ['semester_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    # ### end Alembic commands ###
