"""empty message

Revision ID: 65f2ed3664a5
Revises: d4a211f5ec7d
Create Date: 2025-09-28 16:08:18.918153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f2ed3664a5'
down_revision: Union[str, Sequence[str], None] = 'd4a211f5ec7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('achievement_criteria_achievement_type_id_fkey'), 'achievement_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'achievement_criteria', 'achievement_types', ['achievement_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievement_criteria', type_='foreignkey')
    op.create_foreign_key(op.f('achievement_criteria_achievement_type_id_fkey'), 'achievement_criteria', 'achievement_types', ['achievement_type_id'], ['id'])
    # ### end Alembic commands ###
