"""empty message

Revision ID: 78bb5a14ff4f
Revises: 65f2ed3664a5
Create Date: 2025-09-28 16:22:52.283052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bb5a14ff4f'
down_revision: Union[str, Sequence[str], None] = '65f2ed3664a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_criteria', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('achievement_criteria', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_criteria', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('achievement_criteria', 'name')
    # ### end Alembic commands ###
