"""empty message

Revision ID: 8210a7199d3d
Revises: cb26d78f9fe4
Create Date: 2025-09-26 02:01:06.860050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8210a7199d3d'
down_revision: Union[str, Sequence[str], None] = 'cb26d78f9fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('year_code', sa.String(), nullable=False))
    op.add_column('student_achievements', sa.Column('moderator_comment', sa.String(), nullable=True))
    op.drop_column('student_achievements', 'education_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('education_year', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('student_achievements', 'moderator_comment')
    op.drop_column('student_achievements', 'year_code')
    # ### end Alembic commands ###
