"""empty message

Revision ID: a940adb32cf1
Revises: 2c1309ef88ac
Create Date: 2025-09-26 09:15:02.111049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a940adb32cf1'
down_revision: Union[str, Sequence[str], None] = '2c1309ef88ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_achievements', 'value')
    # ### end Alembic commands ###
