"""empty message

Revision ID: b26ca6ed5ed9
Revises: c1e56181dd66
Create Date: 2025-09-26 01:12:15.668726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26ca6ed5ed9'
down_revision: Union[str, Sequence[str], None] = 'c1e56181dd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('semester_code', sa.String(), nullable=False))
    op.add_column('student_achievements', sa.Column('education_year', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_achievements', 'education_year')
    op.drop_column('student_achievements', 'semester_code')
    # ### end Alembic commands ###
