"""empty message

Revision ID: c1e56181dd66
Revises: c3d4d364cf36
Create Date: 2025-09-26 00:51:47.738354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e56181dd66'
down_revision: Union[str, Sequence[str], None] = 'c3d4d364cf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_achievements', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
