"""empty message

Revision ID: c366a30fc181
Revises: a940adb32cf1
Create Date: 2025-09-26 10:49:41.475316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c366a30fc181'
down_revision: Union[str, Sequence[str], None] = 'a940adb32cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('achievement_criteria_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_achievements_achievement_type_id_fkey'), 'student_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'student_achievements', 'achievement_criteria', ['achievement_criteria_id'], ['id'])
    op.drop_column('student_achievements', 'achievement_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('achievement_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('student_achievements_achievement_type_id_fkey'), 'student_achievements', 'achievement_types', ['achievement_type_id'], ['id'])
    op.drop_column('student_achievements', 'achievement_criteria_id')
    # ### end Alembic commands ###
