"""empty message

Revision ID: c3d4d364cf36
Revises: 971940e05b50
Create Date: 2025-09-26 00:29:59.456785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d4d364cf36'
down_revision: Union[str, Sequence[str], None] = '971940e05b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_criteria', 'max_value')
    op.drop_column('achievement_criteria', 'min_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_criteria', sa.Column('min_value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('achievement_criteria', sa.Column('max_value', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
