"""empty message

Revision ID: cb26d78f9fe4
Revises: b26ca6ed5ed9
Create Date: 2025-09-26 01:36:17.359244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb26d78f9fe4'
down_revision: Union[str, Sequence[str], None] = 'b26ca6ed5ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_achievements', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
