"""empty message

Revision ID: d6e426a773d4
Revises: 8210a7199d3d
Create Date: 2025-09-26 02:03:04.732102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e426a773d4'
down_revision: Union[str, Sequence[str], None] = '8210a7199d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_types', sa.Column('max_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_types', 'max_score')
    # ### end Alembic commands ###
